name: neuron_hud
description: "Sistema de carga y revelado por capas para Flutter, con el lenguaje visual de un HUD holográfico."
version: 1.0.0
repository: https://github.com/sudo-poporin/neuron-hud

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
